name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.11", "1.12", "1.13"]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Lint
        uses: actions-contrib/golangci-lint@v0.1.0

      - name: Test
        run: go test -v ./...

      - name: Build
        run: make build
